name: neon_lints_test
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  nextcloud: ^8.1.0

dev_dependencies:
  custom_lint: ^0.7.1
  flutter_test:
    sdk: flutter
  meta: ^1.11.0
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
