name: nextcloud_test
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  built_collection: ^5.1.1
  collection: ^1.0.0
  cookie_store:
    path: ../../../cookie_store
  glob: ^2.1.2
  http: ^1.2.0
  interceptor_http_client:
    path: ../../../interceptor_http_client
  matcher: ^0.12.0
  meta: ^1.0.0
  nextcloud: ^8.1.0
  path: ^1.9.0
  process_run: ^1.0.0+1
  test: ^1.24.0
  test_api: ^0.7.0
  universal_io: ^2.0.0
  version: ^3.0.0
  xml: ^6.0.0

dev_dependencies:
  neon_lints:
    path: ../../../neon_lints
