name: nextcloud_test_presets
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  crypto: ^3.0.0
  http: ^1.2.0
  meta: ^1.0.0
  nextcloud: ^8.1.0
  version: ^3.0.0

dev_dependencies:
  neon_lints:
    path: ../../../neon_lints
