name: cookie_store
description: A RFC compliant cookie store
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.0.0
  timezone: ^0.10.0

dev_dependencies:
  cookie_store_conformance_tests:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/cookie_store/packages/cookie_store_conformance_tests
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.25.12
