name: cookie_store_conformance_tests
description: >-
  A library that tests whether implementations of package:cookie_store's `CookieStore`
  class behave as expected.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  cookie_store:
    path: ../..
  meta: ^1.0.0
  test: ^1.21.2

dev_dependencies:
  neon_lints:
    path: ../../../neon_lints
