name: Conventional commits
on:
  pull_request:

jobs:
  conventional-commits:
    name: Conventional commits
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install dart
        uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94 # v1
        with:
          sdk: 3.6
      - name: Install commitlint_cli
        run: dart pub global activate commitlint_cli 0.8.1

      - name: Lint conventional commits
        run: dart pub global run commitlint_cli --from=${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to=${{ github.event.pull_request.head.sha }}
